# Generated by Django 3.2.16 on 2022-10-12 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTikets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=250, verbose_name='Причина звернення')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('img', models.ImageField(upload_to='uploads/', verbose_name='Скріншот')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportcompany')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportpriority')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportstatus')),
            ],
            options={
                'verbose_name': 'тікет',
                'verbose_name_plural': 'тікет',
            },
        ),
        migrations.CreateModel(
            name='SupportDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=250, verbose_name='Назва')),
                ('message', models.TextField(verbose_name='Опис розробки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportcompany')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportpriority')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportstatus')),
            ],
            options={
                'verbose_name': 'заявку на розробку',
                'verbose_name_plural': 'заявка на розробку',
            },
        ),
    ]
