# Generated by Django 3.2.16 on 2022-10-12 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportdevelopment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='supportdevelopment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportcompany', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='supportdevelopment',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportpriority', verbose_name='Преорітет'),
        ),
        migrations.AlterField(
            model_name='supporttikets',
            name='created_by',
            field=models.CharField(default=None, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='supporttikets',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportcompany', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='supporttikets',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Скріншот'),
        ),
        migrations.AlterField(
            model_name='supporttikets',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportpriority', verbose_name='Преорітет'),
        ),
    ]
